title: Vania Cortez # your name (or website title) here
logo: "/images/Gitpic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I'm a self-motivated data enthusiast with a passion for using technology to solve real-world problems. Whether I'm creating complex dashboards in Tableau, writing scripts in SQL to extract meaningful insights, or using Excel to analyze and present data in a visually appealing way, I find that working with data is both challenging and rewarding. 
 <br><br>
I pride myself on bringing creativity and originality to every project, working hard to deliver efficient solutions. My favorite part of working with data is finding new ways to analyze, visualize and present data so that others can easily make sense of it. 
 <br><br>
I'm always looking for new ways to use my skills to make a positive impact, and I'm excited to continue growing and developing my expertise in the field of data analytics.
 <br><br>
Hobbies: Traveler & Foodie! 
Pets: Santana The Corgi 
  <br><br>
  <a href="https://www.linkedin.com/in/vaniacortez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



